### ISSUE TITLE
path.startsWith is not a function

### ISSUE THREAD

**Issue by pluveto** [probberechts/hexo-theme-cactus#175]
Reproduce:

1. set `rss: true`
2. `hexo g` => 
```
path.startsWith is not a function
    at Object.urlForHelper (A:\src\blog\node_modules\hexo\lib\plugins\helper\url_for.js:6:31)
    at eval (eval at compile (A:\src\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:120:26)
    at returnedFn (A:\src\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (A:\src\blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (A:\src\blog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (A:\src\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (A:\src\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:14:17)
    at returnedFn (A:\src\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (A:\src\blog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (A:\src\blog\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (A:\src\blog\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (A:\src\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (A:\src\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (A:\src\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (A:\src\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (A:\src\blog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (A:\src\blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (A:\src\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (A:\src\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (A:\src\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
```

if `rss: false` == true then
assert(`the error disapper`==true)

**Comment by probberechts** [comment]
Check the README. `rss: true` is not a valid option.

> Set the `rss` field in the `_config.yml` to one of the following values:
> 1. `rss: false` will totally disable rss (default).
> 2. `rss: atom.xml` sets a specific feed link.
> 3. `rss:`leave empty to use the [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed) plugin.
